ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active' CHECK (status IN ('active', 'blocked'));

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS installments TEXT,
  ADD COLUMN IF NOT EXISTS delivery_type TEXT DEFAULT 'Entrega automatica',
  ADD COLUMN IF NOT EXISTS stock INTEGER,
  ADD COLUMN IF NOT EXISTS sales_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active' CHECK (status IN ('draft', 'active', 'paused', 'rejected'));

ALTER TABLE public.platform_settings
  ADD COLUMN IF NOT EXISTS platform_fee_percent NUMERIC(5,2) DEFAULT 10,
  ADD COLUMN IF NOT EXISTS affiliate_fee_percent NUMERIC(5,2) DEFAULT 5,
  ADD COLUMN IF NOT EXISTS ads_daily_budget NUMERIC(10,2) DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.network_groups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  members INTEGER DEFAULT 0,
  category TEXT NOT NULL,
  link TEXT NOT NULL,
  image_url TEXT,
  sponsored BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.marketing_banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  image_url TEXT,
  mobile_image_url TEXT,
  link_url TEXT DEFAULT '/',
  background_color TEXT DEFAULT '#1E1E1E',
  position TEXT DEFAULT 'home_hero' CHECK (position IN ('home_hero', 'left_flyer', 'right_flyer')),
  sort_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  question TEXT NOT NULL,
  answer TEXT,
  answered_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  title TEXT,
  body TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.seller_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  asset_type TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS products_status_created_idx ON public.products (status, created_at DESC);
CREATE INDEX IF NOT EXISTS products_seller_status_idx ON public.products (seller_id, status);
CREATE INDEX IF NOT EXISTS sales_buyer_created_idx ON public.sales (buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sales_seller_created_idx ON public.sales (seller_id, created_at DESC);
CREATE INDEX IF NOT EXISTS cart_items_user_idx ON public.cart_items (user_id);
CREATE INDEX IF NOT EXISTS network_groups_active_sponsored_idx ON public.network_groups (is_active, sponsored, created_at DESC);
CREATE INDEX IF NOT EXISTS marketing_banners_active_position_idx ON public.marketing_banners (is_active, position, sort_order);

ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.network_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seller_requests ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cart_items' AND policyname = 'Users manage own cart.') THEN
    CREATE POLICY "Users manage own cart." ON public.cart_items FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'network_groups' AND policyname = 'Public groups are viewable.') THEN
    CREATE POLICY "Public groups are viewable." ON public.network_groups FOR SELECT USING (is_active = true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'marketing_banners' AND policyname = 'Public banners are viewable.') THEN
    CREATE POLICY "Public banners are viewable." ON public.marketing_banners FOR SELECT USING (is_active = true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'product_questions' AND policyname = 'Public questions are viewable.') THEN
    CREATE POLICY "Public questions are viewable." ON public.product_questions FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'product_questions' AND policyname = 'Authenticated users ask questions.') THEN
    CREATE POLICY "Authenticated users ask questions." ON public.product_questions FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'product_reviews' AND policyname = 'Public reviews are viewable.') THEN
    CREATE POLICY "Public reviews are viewable." ON public.product_reviews FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'product_reviews' AND policyname = 'Authenticated users create reviews.') THEN
    CREATE POLICY "Authenticated users create reviews." ON public.product_reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'seller_requests' AND policyname = 'Users create seller requests.') THEN
    CREATE POLICY "Users create seller requests." ON public.seller_requests FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'seller_requests' AND policyname = 'Users view own seller requests.') THEN
    CREATE POLICY "Users view own seller requests." ON public.seller_requests FOR SELECT USING (auth.uid() = user_id);
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, role, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'role', 'user'),
    NEW.raw_user_meta_data->>'full_name',
    NEW.email
  )
  ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email,
        full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
DROP POLICY IF EXISTS "Public products are viewable by everyone." ON public.products;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'profiles' AND policyname = 'Users and admins can view profiles.') THEN
    CREATE POLICY "Users and admins can view profiles." ON public.profiles
      FOR SELECT USING (auth.uid() = id OR public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'products' AND policyname = 'Active products are public.') THEN
    CREATE POLICY "Active products are public." ON public.products
      FOR SELECT USING (status = 'active' OR auth.uid() = seller_id OR public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'sales' AND policyname = 'Admins view all sales.') THEN
    CREATE POLICY "Admins view all sales." ON public.sales
      FOR SELECT USING (public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'affiliates' AND policyname = 'Users sellers and admins view affiliates.') THEN
    CREATE POLICY "Users sellers and admins view affiliates." ON public.affiliates
      FOR SELECT USING (auth.uid() = user_id OR auth.uid() = seller_id OR public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'withdrawals' AND policyname = 'Users and admins view withdrawals.') THEN
    CREATE POLICY "Users and admins view withdrawals." ON public.withdrawals
      FOR SELECT USING (auth.uid() = user_id OR public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'network_groups' AND policyname = 'Admins manage groups.') THEN
    CREATE POLICY "Admins manage groups." ON public.network_groups
      FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'marketing_banners' AND policyname = 'Admins manage banners.') THEN
    CREATE POLICY "Admins manage banners." ON public.marketing_banners
      FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'seller_requests' AND policyname = 'Admins view seller requests.') THEN
    CREATE POLICY "Admins view seller requests." ON public.seller_requests
      FOR SELECT USING (public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'seller_requests' AND policyname = 'Admins update seller requests.') THEN
    CREATE POLICY "Admins update seller requests." ON public.seller_requests
      FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'platform_settings' AND policyname = 'Admins update platform settings.') THEN
    CREATE POLICY "Admins update platform settings." ON public.platform_settings
      FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'product_questions' AND policyname = 'Sellers and admins answer questions.') THEN
    CREATE POLICY "Sellers and admins answer questions." ON public.product_questions
      FOR UPDATE USING (
        public.is_admin()
        OR EXISTS (
          SELECT 1 FROM public.products
          WHERE products.id = product_questions.product_id
            AND products.seller_id = auth.uid()
        )
      );
  END IF;
END $$;
