CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  link_url TEXT,
  metadata JSONB DEFAULT '{}'::jsonb,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.affiliates
  DROP CONSTRAINT IF EXISTS affiliates_status_check;

ALTER TABLE public.affiliates
  ADD CONSTRAINT affiliates_status_check
  CHECK (status IN ('pending', 'active', 'inactive'));

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS notifications_user_created_idx
  ON public.notifications (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS notifications_user_unread_idx
  ON public.notifications (user_id, read_at)
  WHERE read_at IS NULL;

DROP POLICY IF EXISTS "Users view own notifications." ON public.notifications;
DROP POLICY IF EXISTS "Users update own notifications." ON public.notifications;
DROP POLICY IF EXISTS "System inserts notifications." ON public.notifications;

CREATE POLICY "Users view own notifications." ON public.notifications
  FOR SELECT USING (auth.uid() = user_id OR public.is_admin());

CREATE POLICY "Users update own notifications." ON public.notifications
  FOR UPDATE USING (auth.uid() = user_id OR public.is_admin())
  WITH CHECK (auth.uid() = user_id OR public.is_admin());

CREATE POLICY "System inserts notifications." ON public.notifications
  FOR INSERT WITH CHECK (auth.uid() = user_id OR public.is_admin());

CREATE OR REPLACE FUNCTION public.create_notification(
  target_user_id UUID,
  notification_type TEXT,
  notification_title TEXT,
  notification_body TEXT DEFAULT NULL,
  notification_link TEXT DEFAULT NULL,
  notification_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF target_user_id IS NULL THEN
    RETURN;
  END IF;

  INSERT INTO public.notifications (user_id, type, title, body, link_url, metadata)
  VALUES (
    target_user_id,
    notification_type,
    notification_title,
    notification_body,
    notification_link,
    COALESCE(notification_metadata, '{}'::jsonb)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.notify_admins(
  notification_type TEXT,
  notification_title TEXT,
  notification_body TEXT DEFAULT NULL,
  notification_link TEXT DEFAULT NULL,
  notification_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  admin_row RECORD;
BEGIN
  FOR admin_row IN
    SELECT id
    FROM public.profiles
    WHERE role = 'admin'
      AND COALESCE(status, 'active') = 'active'
  LOOP
    PERFORM public.create_notification(
      admin_row.id,
      notification_type,
      notification_title,
      notification_body,
      notification_link,
      notification_metadata
    );
  END LOOP;
END;
$$;

DROP POLICY IF EXISTS "Users accept own affiliate invitations." ON public.affiliates;
CREATE POLICY "Users accept own affiliate invitations." ON public.affiliates
  FOR UPDATE USING (auth.uid() = user_id AND status = 'pending')
  WITH CHECK (auth.uid() = user_id AND status = 'active');

CREATE OR REPLACE FUNCTION public.notify_affiliate_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  seller_name TEXT;
  affiliate_name TEXT;
  product_title TEXT;
BEGIN
  SELECT COALESCE(store_name, full_name, 'Vendedor') INTO seller_name
  FROM public.profiles
  WHERE id = NEW.seller_id;

  SELECT COALESCE(full_name, email, 'Afiliado') INTO affiliate_name
  FROM public.profiles
  WHERE id = NEW.user_id;

  SELECT title INTO product_title
  FROM public.products
  WHERE id = NEW.product_id;

  IF TG_OP = 'INSERT' AND NEW.status = 'pending' THEN
    PERFORM public.create_notification(
      NEW.user_id,
      'affiliate_invite',
      'Convite de afiliado',
      seller_name || ' convidou voce para ser afiliado.',
      '/painel/usuario/afiliacoes',
      jsonb_build_object('affiliate_id', NEW.id, 'seller_id', NEW.seller_id)
    );
  ELSIF TG_OP = 'INSERT' AND NEW.status = 'active' THEN
    PERFORM public.create_notification(
      NEW.seller_id,
      'affiliate_joined',
      'Novo afiliado',
      affiliate_name || ' se afiliou' || CASE WHEN product_title IS NOT NULL THEN ' ao produto ' || product_title ELSE ' a sua loja' END || '.',
      '/painel/vendedor/afiliados',
      jsonb_build_object('affiliate_id', NEW.id, 'user_id', NEW.user_id, 'product_id', NEW.product_id)
    );
    PERFORM public.notify_admins(
      'affiliate_joined',
      'Novo afiliado',
      affiliate_name || ' se afiliou' || CASE WHEN product_title IS NOT NULL THEN ' ao produto ' || product_title ELSE ' a uma loja' END || '.',
      '/painel/admin/afiliados',
      jsonb_build_object('affiliate_id', NEW.id, 'user_id', NEW.user_id, 'seller_id', NEW.seller_id, 'product_id', NEW.product_id)
    );
  ELSIF TG_OP = 'UPDATE' AND OLD.status IS DISTINCT FROM NEW.status AND NEW.status = 'active' THEN
    PERFORM public.create_notification(
      NEW.seller_id,
      'affiliate_invite_accepted',
      'Convite aceito',
      affiliate_name || ' aceitou seu convite de afiliado.',
      '/painel/vendedor/afiliados',
      jsonb_build_object('affiliate_id', NEW.id, 'user_id', NEW.user_id)
    );
    PERFORM public.notify_admins(
      'affiliate_invite_accepted',
      'Convite de afiliado aceito',
      affiliate_name || ' aceitou um convite de afiliado.',
      '/painel/admin/afiliados',
      jsonb_build_object('affiliate_id', NEW.id, 'user_id', NEW.user_id, 'seller_id', NEW.seller_id)
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_affiliate_change ON public.affiliates;
CREATE TRIGGER notify_affiliate_change
  AFTER INSERT OR UPDATE OF status
  ON public.affiliates
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_affiliate_change();

CREATE OR REPLACE FUNCTION public.notify_sale_created()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  product_title TEXT;
BEGIN
  SELECT title INTO product_title
  FROM public.products
  WHERE id = NEW.product_id;

  IF NEW.seller_id IS NOT NULL THEN
    PERFORM public.create_notification(
      NEW.seller_id,
      'sale_created',
      'Nova venda recebida',
      COALESCE(product_title, 'Produto') || ' teve uma nova transacao.',
      '/painel/vendedor/vendas',
      jsonb_build_object('sale_id', NEW.id, 'product_id', NEW.product_id, 'status', NEW.status)
    );
  END IF;

  PERFORM public.notify_admins(
    'sale_created',
    'Nova transacao na plataforma',
    COALESCE(product_title, 'Produto/ferramenta') || ' gerou uma nova transacao.',
    '/painel/admin/financeiro',
    jsonb_build_object('sale_id', NEW.id, 'product_id', NEW.product_id, 'seller_id', NEW.seller_id, 'status', NEW.status)
  );

  IF NEW.buyer_id IS NOT NULL THEN
    PERFORM public.create_notification(
      NEW.buyer_id,
      'purchase_created',
      'Compra registrada',
      'Seu pedido foi criado e esta no historico de compras.',
      '/painel/usuario/compras',
      jsonb_build_object('sale_id', NEW.id, 'product_id', NEW.product_id, 'status', NEW.status)
    );
  END IF;

  IF NEW.affiliate_user_id IS NOT NULL THEN
    PERFORM public.create_notification(
      NEW.affiliate_user_id,
      'affiliate_commission',
      CASE WHEN NEW.affiliate_source = 'linkbio' THEN 'Comissao linkbio' ELSE 'Comissao de afiliado' END,
      'Uma venda gerou comissao para voce.',
      CASE WHEN NEW.affiliate_source = 'linkbio' THEN '/painel/vendedor/vendas' ELSE '/painel/usuario/afiliacoes' END,
      jsonb_build_object('sale_id', NEW.id, 'amount', NEW.affiliate_commission_amount, 'source', NEW.affiliate_source)
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_sale_created ON public.sales;
CREATE TRIGGER notify_sale_created
  AFTER INSERT
  ON public.sales
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_sale_created();

CREATE OR REPLACE FUNCTION public.notify_product_question()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  seller_uuid UUID;
  product_title TEXT;
BEGIN
  SELECT seller_id, title INTO seller_uuid, product_title
  FROM public.products
  WHERE id = NEW.product_id;

  PERFORM public.create_notification(
    seller_uuid,
    'product_question',
    'Nova pergunta no produto',
    'Chegou uma pergunta em ' || COALESCE(product_title, 'um produto') || '.',
    '/produto/' || NEW.product_id::text,
    jsonb_build_object('question_id', NEW.id, 'product_id', NEW.product_id)
  );

  PERFORM public.notify_admins(
    'product_question',
    'Nova pergunta na plataforma',
    'Chegou uma pergunta em ' || COALESCE(product_title, 'um produto') || '.',
    '/painel/admin/perguntas',
    jsonb_build_object('question_id', NEW.id, 'product_id', NEW.product_id, 'seller_id', seller_uuid)
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_product_question ON public.product_questions;
CREATE TRIGGER notify_product_question
  AFTER INSERT
  ON public.product_questions
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_product_question();

CREATE OR REPLACE FUNCTION public.notify_product_status()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF OLD.status IS DISTINCT FROM NEW.status AND NEW.status = 'active' THEN
    PERFORM public.create_notification(
      NEW.seller_id,
      'product_approved',
      'Produto liberado',
      NEW.title || ' foi liberado na loja.',
      '/painel/vendedor/anuncios',
      jsonb_build_object('product_id', NEW.id)
    );
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_product_status ON public.products;
CREATE TRIGGER notify_product_status
  AFTER UPDATE OF status
  ON public.products
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_product_status();
