CREATE TABLE IF NOT EXISTS public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (user_id, product_id)
);

CREATE INDEX IF NOT EXISTS cart_items_user_idx ON public.cart_items (user_id);
CREATE INDEX IF NOT EXISTS sales_buyer_created_idx ON public.sales (buyer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sales_seller_created_idx ON public.sales (seller_id, created_at DESC);

ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND role = 'admin'
  );
$$;

DO $$
BEGIN
  DROP POLICY IF EXISTS "Users manage own cart." ON public.cart_items;
  DROP POLICY IF EXISTS "Users view own purchases." ON public.sales;
  DROP POLICY IF EXISTS "Buyers create pending sales." ON public.sales;

  CREATE POLICY "Users manage own cart." ON public.cart_items
    FOR ALL USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

  CREATE POLICY "Users view own purchases." ON public.sales
    FOR SELECT USING (
      auth.uid() = buyer_id
      OR auth.uid() = seller_id
      OR public.is_admin()
    );

  CREATE POLICY "Buyers create pending sales." ON public.sales
    FOR INSERT WITH CHECK (
      auth.uid() = buyer_id
      AND status = 'pending'
      AND EXISTS (
        SELECT 1
        FROM public.products
        WHERE products.id = sales.product_id
          AND products.seller_id = sales.seller_id
          AND products.price = sales.amount
          AND products.status = 'active'
      )
    );
END $$;
