CREATE TABLE IF NOT EXISTS public.product_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_searches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query TEXT NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  matched_category TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS product_clicks_product_created_idx
  ON public.product_clicks (product_id, created_at DESC);

CREATE INDEX IF NOT EXISTS product_clicks_category_created_idx
  ON public.product_clicks (category, created_at DESC);

CREATE INDEX IF NOT EXISTS product_searches_category_created_idx
  ON public.product_searches (matched_category, created_at DESC);

ALTER TABLE public.product_clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_searches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can register product clicks." ON public.product_clicks;
CREATE POLICY "Anyone can register product clicks."
  ON public.product_clicks
  FOR INSERT
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Anyone can register product searches." ON public.product_searches;
CREATE POLICY "Anyone can register product searches."
  ON public.product_searches
  FOR INSERT
  WITH CHECK (user_id IS NULL OR auth.uid() = user_id);

DROP POLICY IF EXISTS "Product clicks are readable by everyone." ON public.product_clicks;
CREATE POLICY "Product clicks are readable by everyone."
  ON public.product_clicks
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Product searches are readable by everyone." ON public.product_searches;
CREATE POLICY "Product searches are readable by everyone."
  ON public.product_searches
  FOR SELECT
  USING (true);
