ALTER TABLE public.platform_settings
  ADD COLUMN IF NOT EXISTS wallet_withdrawal_fee_percent NUMERIC(5,2) DEFAULT 5;

CREATE TABLE IF NOT EXISTS public.wallet_deposits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled')),
  payment_gateway TEXT,
  payment_external_ref TEXT,
  payment_transaction_id TEXT,
  payment_qrcode TEXT,
  payment_qrcode_text TEXT,
  payment_qrcode_expires_at TIMESTAMP WITH TIME ZONE,
  gateway_payload JSONB,
  paid_at TIMESTAMP WITH TIME ZONE,
  available_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.withdrawals
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'earnings' CHECK (source IN ('earnings', 'wallet')),
  ADD COLUMN IF NOT EXISTS gross_amount NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS fee_amount NUMERIC(10,2) DEFAULT 0;

CREATE INDEX IF NOT EXISTS wallet_deposits_user_created_idx
  ON public.wallet_deposits (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS wallet_deposits_available_idx
  ON public.wallet_deposits (user_id, status, available_at);

ALTER TABLE public.wallet_deposits ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.user_wallet_available_balance(target_user UUID)
RETURNS NUMERIC
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH deposits AS (
    SELECT COALESCE(SUM(amount), 0) AS total
      FROM public.wallet_deposits
     WHERE user_id = target_user
       AND status = 'paid'
       AND available_at IS NOT NULL
       AND available_at <= now()
  ),
  withdrawals_total AS (
    SELECT COALESCE(SUM(COALESCE(gross_amount, amount)), 0) AS total
      FROM public.withdrawals
     WHERE user_id = target_user
       AND source = 'wallet'
       AND status IN ('pending', 'paid')
  )
  SELECT GREATEST((SELECT total FROM deposits) - (SELECT total FROM withdrawals_total), 0);
$$;

CREATE OR REPLACE FUNCTION public.validate_wallet_withdrawal()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  available_balance NUMERIC;
  fee_percent NUMERIC;
  requested_gross NUMERIC;
BEGIN
  IF NEW.source IS DISTINCT FROM 'wallet' THEN
    RETURN NEW;
  END IF;

  IF NEW.user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'Saque invalido';
  END IF;

  requested_gross := COALESCE(NEW.gross_amount, NEW.amount);
  IF requested_gross <= 0 THEN
    RAISE EXCEPTION 'Valor de saque invalido';
  END IF;

  available_balance := public.user_wallet_available_balance(NEW.user_id);
  IF requested_gross > available_balance THEN
    RAISE EXCEPTION 'Saldo insuficiente';
  END IF;

  SELECT COALESCE(wallet_withdrawal_fee_percent, 0)
    INTO fee_percent
    FROM public.platform_settings
   WHERE id = 1;

  NEW.gross_amount := requested_gross;
  NEW.fee_amount := ROUND((requested_gross * COALESCE(fee_percent, 0) / 100)::numeric, 2);
  NEW.amount := GREATEST(requested_gross - NEW.fee_amount, 0);

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS validate_wallet_withdrawal ON public.withdrawals;
CREATE TRIGGER validate_wallet_withdrawal
  BEFORE INSERT ON public.withdrawals
  FOR EACH ROW
  EXECUTE FUNCTION public.validate_wallet_withdrawal();

DO $$
BEGIN
  DROP POLICY IF EXISTS "Users view own wallet deposits." ON public.wallet_deposits;
  DROP POLICY IF EXISTS "Users create own wallet deposits." ON public.wallet_deposits;
  DROP POLICY IF EXISTS "Users cancel own pending wallet deposits." ON public.wallet_deposits;
  DROP POLICY IF EXISTS "Admins view wallet deposits." ON public.wallet_deposits;
  DROP POLICY IF EXISTS "Users create own withdrawals." ON public.withdrawals;

  CREATE POLICY "Users view own wallet deposits." ON public.wallet_deposits
    FOR SELECT USING (auth.uid() = user_id);

  CREATE POLICY "Users create own wallet deposits." ON public.wallet_deposits
    FOR INSERT WITH CHECK (auth.uid() = user_id);

  CREATE POLICY "Users cancel own pending wallet deposits." ON public.wallet_deposits
    FOR UPDATE USING (auth.uid() = user_id AND status = 'pending')
    WITH CHECK (auth.uid() = user_id AND status = 'cancelled');

  CREATE POLICY "Admins view wallet deposits." ON public.wallet_deposits
    FOR SELECT USING (public.is_admin());

  CREATE POLICY "Users create own withdrawals." ON public.withdrawals
    FOR INSERT WITH CHECK (auth.uid() = user_id);
END $$;

GRANT SELECT, INSERT, UPDATE ON public.wallet_deposits TO authenticated;
